apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: default
  namespace: acd
spec:
  project: default
  source:
    chart: dev-0.1.0
    repoURL: https://github.com/Monzy-B/argocd_manifests
    targetRevision: 1.16.1
    helm:
      valueFiles: 
        - ./helm/helmvars/alpha/values.yaml
      releaseName: argo-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: acd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
