apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: default
  namespace: acd
spec:
  project: default
  source:
    repoURL: https://github.com/Monzy-B/argocd_manifests
    targetRevision: development
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: acd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
