apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: ArgoCD Project
  namespace: acd
spec:
  project: default
  source:
    repoURL: 
    targetRevision: main
    path: dev-k8s
  destination:
    server: 
    namespace: ArgoCD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true